### PR TITLE
URL Aliases Module

### PR DESCRIPTION
**Pull request by isaacmg410**
#### :tophat: What? Why?
Decidim gem to allow admins to create url aliases for resources.

#### :pushpin: Related Issues
- Related to [Alias url for participatory spaces #4](https://github.com/OpenSourcePolitics/dev/issues/4)
- Related to [Listing and defining forbidden paths #2](https://github.com/OpenSourcePolitics/decidim-urlaliases/issues/2)

#### :clipboard: Subtasks
- [ ] Add `CHANGELOG` entry
- [x] Add tests

#### Url Aliases button
url_aliases_button

#### Redirect rules index
redirect_rules_index

#### New redirect rule
new_redirect_rule

#### Edit redirect rule
edit_redirect_rule

### CODE REVIEW

**Comment by virgile-dev** [comment]
@isaacmg410 @aitorlb looking good !

Only bug I found: 
I tried to uncheck the `active` checkbox but it had no effect the alias I created kept working.
Capture d’écran 2019-08-29 à 16 43 34
Thanks in advance !

**Comment by aitorlb** [comment]
@virgile-dev , as the README says, this is an unfortunate problem with the web-browser:
> Disclaimer: be aware that you may have to clear your web browser cache after making changes to an existing redirect rule to be redirected to the new destination.

**Comment by virgile-dev** [comment]
@aitorlb Thanks for the good work, I've demoed the module to the client and they are quite happy with.

## Couple feedback they made : 
* It is not currently possible to put a document url as a destination 
Capture d’écran 2019-09-06 à 11 47 22

* Also I've noticed the current way the module is designed it only accept destination urls that come from a process. In the first place I wrote in the issue that the module was for participatory spaces.
--> It should work for assemblies, initiatives, consultations 

Now that I think of it maybe that limitation was bit foolish, we should accept aliases for anything in Decidim. @valentinchaput can you provide feedback on this ?

@isaacmg410 is that a big change in the code or is it easy to allow ?

* Last thing about the destination url fied,  I noticed that most fields in Decidim where a path needs to be input they don't accept / as first character. Do you think we should harmonize ?
Capture d’écran 2019-09-06 à 12 21 43

**Comment by aitorlb** [comment]
Hi @virgile-dev , thanks for the feedback. My answer:

> It is not currently possible to put a document url as a destination

It is not, but it can be changed. However, wouldn't it be easier to redirect to the decidim resource that the document is attached to?

The reason it is not currently possible is stated in the README:

> Only paths that match public routes within participatory spaces are allowed as destination.

--

> Also I've noticed the current way the module is designed it only accept destination urls that come from a process. In the first place I wrote in the issue that the module was for participatory spaces.
--> It should work for assemblies, initiatives, consultations

Is this a feedback from your client or have you experienced it yourself? As stated above, that is indeed the way it works.

The module does not care about any particular participatory space more than the others, it just collects all the routes from all participatory spaces and compares them with the destination, if it matches any of them, then it is accepted. This should work for new spaces too.

This is from local development:

redirect_rules_from_spaces

--
> Now that I think of it maybe that limitation was bit foolish, we should accept aliases for anything in Decidim.

I don't think it was foolish, I think it was a smart decision. Have you though of anything in particular that would be out of bounds of the current implementation? (aside from attachments)

We currently accept **anything** in Decidim **within participatory spaces**, and that allows for destination validation. Knowing that amost everything in decidim lies between the following relationship, I think we cover enough ground:

> resource < component < participatory_space < organization

--

> Last thing about the destination url fied, I noticed that most fields in Decidim where a path needs to be input they don't accept / as first character. Do you think we should harmonize ?

I agree that this module behaves different and efforts can be made to harmonize that aspect. 

I personally would advise against it, as it would add unnecessary complexity for a matter that is mostly aesthetic. The way the `redirector` gem works, the path must be saved to the database **with the slash**. In fact, I had an implementation where the slash was removed for the front-end and then added again for the back-end but regressed from it, because it was unnecessary complex.

Also, I found that the slash makes it obvious that you are dealing with **paths**. In decidim, the slug is part of a larger path and they have to provide an example to make it clear what it is that you are creating.

slug_example

In our case, we don't mention anywhere that the path will be prepended by the organization host, but I think the process is clear enough and that the slash helps conveying that.

But then again, it can be changed.

**Comment by aitorlb** [comment]
@virgile-dev,

> I tried to uncheck the active checkbox but it had no effect the alias I created kept working.

The code has been updated so this should work as expected now.

**Comment by virgile-dev** [comment]
Thanks @aitorlb for your feedback.
> It is not, but it can be changed. However, wouldn't it be easier to redirect to the decidim resource that the document is attached to?

Not really, it's a special request for our client. If you can adjust to make it work it would be awesome.

> I agree that this module behaves different and efforts can be made to harmonize that aspect.

I agree that the slash make it clearer than the way it is implemented in the rest of Decidim. Let's keep it this way. 

>I don't think it was foolish, I think it was a smart decision. Have you though of anything in particular that would be out of bounds of the current implementation? (aside from attachments)

I was thinking you might have an alias for pages. Ex : /pages/terms-and-conditions
From a functionnal perspective I guess I thought there is no point in limiting the destination possibilities. But now that I understand that you use it to check if the destination exists it makes sense why it was not foolish. Let's keep it this way as extended it would be out of the scope and budget. 

Plus I just tried with the rest of the spaces it indeed works so no issue there ! Thanks @aitorlb for the 
awesome work.

**Comment by aitorlb** [comment]
@virgile-dev,

> Not really, it's a special request for our client. If you can adjust to make it work it would be awesome.

**/uploads** is now accepted as destination. For more flexibility, exceptions can now be added by overriding constants in an initializer.

Consider though, that if the application uses some form of cloud storage the redirection won't work because the host is not the same ([example](https://codit-decidim-santcugat.s3.amazonaws.com/uploads/decidim/attachment/file/132/Resultats_votacions_Pressupostos_Participatius_2018_web_v3.pdf)).

**Comment by virgile-dev** [comment]
No more issues here for me. @armandfardeau or @moustachu you guys can merge if you deem appropriate. We now need to make sure that it works with our 0.16 stable.

**Review by moustachu — APPROVED** [review]

**Comment by moustachu** [comment]
@aitorlb I would have created an issue but you might not have been notified since your not part of this repo and the on on your side does not accept issues.

It seems that we just miss the proper migration for the `redirect_rules` we only have the one that add the link to the organization  :
https://github.com/OpenSourcePolitics/decidim-urlaliases/tree/master/db/migrate

Could you generate it from your dev environment ? 

This should have been detected sooner if I had made the proper tests before merging ... sorry for that.

Regards

**Comment by isaacmg410** [comment]
@moustachu only as information and to close the pull request "correctly".

As @aitorlb said in the chat, if you execute the rake task (`bundle exec rake url_aliases:init`) copies and installs the necessary migrations of both, the gem and its dependencies, to the application.

Then, this is not necessary to be do:
> It seems that we just miss the proper migration for the redirect_rules we only have the one that add the link to the organization :
> https://github.com/OpenSourcePolitics/decidim-urlaliases/tree/master/db/migrate
> 
> Could you generate it from your dev environment ?

**Pull request merged**
